%YAML 1.1
---

vars:
  address-groups:
    HOME_NET: "[172.28.0.0/16, 127.0.0.1/32, 192.168.0.0/16, 10.0.0.0/8]"
    EXTERNAL_NET: "!$HOME_NET"
    HTTP_SERVERS: "$HOME_NET"
  port-groups:
    HTTP_PORTS: "80, 8000, 8080, 6333"

default-log-dir: /var/log/suricata

outputs:
  - eve-log:
      enabled: yes
      filetype: regular
      filename: eve.json
      types:
        - alert:
            payload: yes
            payload-buffer-size: 4kb
            payload-printable: yes
            packet: yes
            metadata: yes
            http-body: yes
            http-body-printable: yes
            tagged-packets: yes
        - http:
            extended: yes
        - dns:
            version: 2
        - flow
        - netflow

af-packet:
  - interface: eth0
    threads: auto
    cluster-id: 99
    cluster-type: cluster_flow
    defrag: yes
    use-mmap: yes
    mmap-locked: yes

app-layer:
  protocols:
    http:
      enabled: yes
      libhtp:
        default-config:
          personality: IDS
          request-body-limit: 1048576
          response-body-limit: 1048576

default-rule-path: /var/lib/suricata/rules

rule-files:
  - prompt_injection.rules
  - llm_exfiltration.rules
